language: ruby
rvm:
  - 2.2
before_install:
  - gem install jekyll bundle sass
#  - openssl aes-256-cbc -K $encrypted_b1b8ee34d90c_key -iv $encrypted_b1b8ee34d90c_iv -in deploy_key.enc -out ~\/.ssh/deploy_key -d
env:
  global:
  - GH_REF: github.com/johnpryan/johnpryan.github.com.git
#  - COMMIT_AUTHOR_EMAIL: john.p.ryan4@gmail.com
script: bash ./deploy.sh
deploy:
  local-dir: _site
  repo: johnpryan/johnpryan.github.io
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  on:
    branch: master