language: dart
dart:
  - stable
env:
  global:
  - GH_REF: github.com/johnpryan/johnpryan.github.com.git
  - secure: "RqjxwUCn2PA07JiPVJpRY0zREG2PtuPb9FM9YjCwBStO8m96krt4KU2VGDkRdiyPQIbc4hVmsUuQv8pi3Efddxwwei2R6dGCCuXWBM4/geMIbDoCe4j8XjvRzS7YLAYK085Ux0bTJ6emxR4uA4ReNqYZilfltL9PmyyA2nyuazYkJlSx33jHMfKAozgKa36oD6keYuZn0JAXHAmGUbzs8/Qto9357nd6Pt0DfPCJTHZzrTF7eIis4XTbrEvfVJ9pEj4JadxWf8o+mnP/V2DpadjhOCZSClkcEUuV+CJK9zXd4WxBpzlQxTqkOUsXe6Iisfww0Y846Oo/L51mWhqnEJJcaqe+YhxUNb2YPOg9TLBEGOilE50t+hXnGRk0H0Q8+h4G1lxLXHzm0loisGlE6qbwSSouqIDee9ACryODyugTycr6T0X9YePD6Ge7pmU+j/L/eZ4Yy7wdr5GRRdixiIVnNQ+jKjPVOUPHd4daBnWk+rMirXnoqCLhHW3/k5v/KVHpMmhvV2FYd3wVn4vttKsrcZODX3Xpa6Bq40ZsQ98N73bsZP1B6eNLVT7mQuuzEwyBlNGApki90W/uwAGJYhpsLuPneS3BnIFpONvoYVkt12QbcDT3yebh5mFYXZPz2LrBLbuFIm1Gia77lnZExRIx5DjCk90ytXCfocaP9qU="
script: bash ./deploy.sh